DROP SCHEMA IF EXISTS bus_manager;
CREATE SCHEMA bus_manager CHARACTER SET utf8;
USE bus_manager;

CREATE TABLE IF NOT EXISTS PASSENGER (
    PASSENGER_NAME varchar(20) NOT NULL,
    PASSENGER_SURNAME varchar(20) NOT NULL,
    PASSENGER_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS DRIVER(
    PHONE_NUMBER varchar(20),
    LICENCE_EXPIRE DATE,
    DRIVER_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
    DRIVER_NAME varchar(20) NOT NULL,
    DRIVER_SURNAME varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS BUS(
    REGISTRATION_NUMBER varchar(10) NOT NULL UNIQUE,
    LAST_TI DATE,
    NEXT_TI DATE,
    BUS_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    BUS_MODEL VARCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS JOURNEY(
    DRIVER_ID INTEGER,
    BUS_ID INTEGER,
    JOURNEY_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    LEAVING_DATE DATE,
    ARRIVING_DATE DATE,
    FROM_PLACE VARCHAR(100),
    DESTINATION VARCHAR(100),
    constraint journey_fk_1 foreign key (DRIVER_ID) references DRIVER(DRIVER_ID) ON DELETE set null ON UPDATE NO ACTION,
    constraint journey_fk_2 foreign key (BUS_ID) references BUS(BUS_ID) ON DELETE set null ON UPDATE NO ACTION
);


CREATE TABLE IF NOT EXISTS JOURNEYS_PASSENGERS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
    PASSENGER_ID INTEGER,
    JOURNEY_ID INTEGER,
    constraint jc_fk_1 foreign key (PASSENGER_ID) references PASSENGER(PASSENGER_ID) ON DELETE SET NULL ON UPDATE NO ACTION,
    constraint jc_fk_2 foreign key (JOURNEY_ID) references JOURNEY(JOURNEY_ID) ON DELETE SET NULL ON UPDATE NO ACTION
);

