DROP SCHEMA IF EXISTS bus_manager;
CREATE SCHEMA bus_manager CHARACTER SET utf8;
USE bus_manager;

CREATE TABLE IF NOT EXISTS PASSENGER (
  PASSENGER_NAME varchar(20) NOT NULL,
  PASSENGER_SURNAME varchar(20) NOT NULL,
  PASSENGER_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS DRIVER(
  PHONE_NUMBER varchar(20),
  LICENCE_EXPIRE DATE,
  DRIVER_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
  DRIVER_NAME varchar(20) NOT NULL,
  DRIVER_SURNAME varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS BUS(
  REGISTRATION_NUMBER varchar(10) NOT NULL UNIQUE,
  LAST_TI DATE,
  NEXT_TI DATE,
  BUS_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  BUS_MODEL VARCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS JOURNEY(
  DRIVER_ID INTEGER,
  BUS_ID INTEGER,
  JOURNEY_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  LEAVING_DATE DATE,
  ARRIVING_DATE DATE,
  FROM_PLACE VARCHAR(100),
  DESTINATION VARCHAR(100),
  constraint journey_fk_1 foreign key (DRIVER_ID) references DRIVER(DRIVER_ID) ON DELETE set null ON UPDATE NO ACTION,
  constraint journey_fk_2 foreign key (BUS_ID) references BUS(BUS_ID) ON DELETE set null ON UPDATE NO ACTION
);


CREATE TABLE IF NOT EXISTS JOURNEYS_PASSENGERS(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
  PASSENGER_ID INTEGER,
  JOURNEY_ID INTEGER,
  constraint jc_fk_1 foreign key (PASSENGER_ID) references PASSENGER(PASSENGER_ID) ON DELETE SET NULL ON UPDATE NO ACTION,
  constraint jc_fk_2 foreign key (JOURNEY_ID) references JOURNEY(JOURNEY_ID) ON DELETE SET NULL ON UPDATE NO ACTION
);

INSERT INTO BUS (REGISTRATION_NUMBER, LAST_TI, NEXT_TI,BUS_MODEL)
VALUES ("AE 1595", '20120516','20180619', "Audi");
INSERT INTO BUS (REGISTRATION_NUMBER, LAST_TI, NEXT_TI,BUS_MODEL)
VALUES ("AE 2094", '20150617','20200711', "Toyota");
INSERT INTO BUS (REGISTRATION_NUMBER, LAST_TI, NEXT_TI,BUS_MODEL)
VALUES ("AP 1312", '20170316','20190619', "BIG_BUS");
INSERT INTO BUS (REGISTRATION_NUMBER, LAST_TI, NEXT_TI,BUS_MODEL)
VALUES ("AE 2034", '20131119','20180612', "ROCKET");
INSERT INTO DRIVER (PHONE_NUMBER, LICENCE_EXPIRE, DRIVER_NAME, DRIVER_SURNAME)
VALUES ("050-974-48-50", "20201219","Виктор", "Князев");
INSERT INTO DRIVER (PHONE_NUMBER, LICENCE_EXPIRE, DRIVER_NAME, DRIVER_SURNAME)
VALUES ("067-935-98-51", '20250610', "Василий", "Миронов");
INSERT INTO DRIVER (PHONE_NUMBER, LICENCE_EXPIRE, DRIVER_NAME, DRIVER_SURNAME)
VALUES ("066-999-33-50", '20300920', "Борис", "Сложный");
INSERT INTO JOURNEY (DRIVER_ID, BUS_ID, LEAVING_DATE, ARRIVING_DATE, FROM_PLACE, DESTINATION)
VALUES (1,1,'20170715','20170717',"Днепр", "Одесса");
INSERT INTO JOURNEY (DRIVER_ID, BUS_ID, LEAVING_DATE, ARRIVING_DATE, FROM_PLACE, DESTINATION)
VALUES (3,4,'20170712','20170714',"Ужгород", "Харьков");
INSERT INTO JOURNEY (DRIVER_ID, BUS_ID, LEAVING_DATE, ARRIVING_DATE, FROM_PLACE, DESTINATION)
VALUES (3,2,'20170810','20170812',"Геническ", "Тернополь");
INSERT INTO JOURNEY (DRIVER_ID, BUS_ID, LEAVING_DATE, ARRIVING_DATE, FROM_PLACE, DESTINATION)
VALUES (2,3,'20170905','20170906',"Киев", "Запорожье");
INSERT INTO JOURNEY (DRIVER_ID, BUS_ID, LEAVING_DATE, ARRIVING_DATE, FROM_PLACE, DESTINATION)
VALUES (1,3,'20170721','20170723',"Черкассы", "Одесса");
INSERT INTO JOURNEY (DRIVER_ID, BUS_ID, LEAVING_DATE, ARRIVING_DATE, FROM_PLACE, DESTINATION)
VALUES (1,1,'20170715','20170717',"Днепр", "Николаев");
INSERT INTO JOURNEY (DRIVER_ID, BUS_ID, LEAVING_DATE, ARRIVING_DATE, FROM_PLACE, DESTINATION)
VALUES (3,3,'20171015','20171018',"Симферополь", "Запорожье");
INSERT INTO JOURNEY (DRIVER_ID, BUS_ID, LEAVING_DATE, ARRIVING_DATE, FROM_PLACE, DESTINATION)
VALUES (2,2,'20170915','20170918',"Бердянск", "Львов");
INSERT INTO PASSENGER (PASSENGER_NAME, PASSENGER_SURNAME)
VALUES ("Виктор", "Белый");
INSERT INTO PASSENGER (PASSENGER_NAME, PASSENGER_SURNAME)
VALUES ("Валентин", "Мазур");
INSERT INTO PASSENGER (PASSENGER_NAME, PASSENGER_SURNAME)
VALUES ("Авдотья", "Седогрив");
INSERT INTO PASSENGER (PASSENGER_NAME, PASSENGER_SURNAME)
VALUES ("Геральт", "Ривийский");
INSERT INTO PASSENGER (PASSENGER_NAME, PASSENGER_SURNAME)
VALUES ("Лидия", "Синежабрая");
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (1, 1);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (2, 1);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (3, 1);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (4, 2);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (5, 2);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (2, 2);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (3, 3);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (4, 8);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (5, 8);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (4, 7);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (3, 5);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (1, 5);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (5, 6);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (2, 7);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (4, 3);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (5, 2);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (1, 6);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (2, 8);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (1, 1);
INSERT INTO JOURNEYS_PASSENGERS (PASSENGER_ID, JOURNEY_ID) VALUES (4, 4);